Fixed Navbar UI
acm-ucr/isa-website pull request #112
Opened 2024-02-05 21:42 UTC by raulrazo

Screenshots showing mobile responsiveness are included.
![Screenshot 2024-02-05 at 1 40 37 PM](https://github.com/acm-ucr/isa-website/assets/129914276/80ccbbb4-b88c-430d-aade-d9863741615a)
![Screenshot 2024-02-05 at 1 38 37 PM](https://github.com/acm-ucr/isa-website/assets/129914276/d95ca9dc-5a2e-4458-b603-c7a319950a83)
![Screenshot 2024-02-05 at 1 38 21 PM](https://github.com/acm-ucr/isa-website/assets/129914276/e74a59eb-b9fa-46b9-9fa9-4c3f52218085)
![Screenshot 2024-02-05 at 1 37 27 PM](https://github.com/acm-ucr/isa-website/assets/129914276/a23313b9-d469-4244-ac25-8e2b1414e1bb)
![Screenshot 2024-02-05 at 1 37 17 PM](https://github.com/acm-ucr/isa-website/assets/129914276/5439b99a-309a-4c3b-8a1b-db0b8829cfba)

2024-02-05 22:25 UTC, seanquiambao requested changes
<img width="561" alt="image" src="https://github.com/acm-ucr/isa-website/assets/91030482/7b961050-3713-413e-8c87-ca80be1a27cc">

everything else looks fine, but make sure the navigation bar is mobile responsive. reduce the amount of space between the items

2024-02-05 23:55 UTC, raulrazo commented
Here are my updates to the mobile navbar:
![Screenshot 2024-02-05 at 3 49 43 PM](https://github.com/acm-ucr/isa-website/assets/129914276/e22e3d29-226e-4a6d-8969-61f5ab3dbd6b)
![Screenshot 2024-02-05 at 3 50 06 PM](https://github.com/acm-ucr/isa-website/assets/129914276/120e732a-f8d0-4df2-9fbb-00b7a3d10013)
![Screenshot 2024-02-05 at 3 50 16 PM](https://github.com/acm-ucr/isa-website/assets/129914276/558348da-4d49-4111-90c0-6697a30d6d16)

2024-02-06 06:20 UTC, seanquiambao requested changes

2024-02-06 06:20 UTC, seanquiambao commented on src/components/Navigation.jsx
> +            className="flex justify-center items-center text-white text-3xl font-bold w-44 h-11 rounded-full bg-gradient-to-r from-isa-yellow-200 to-isa-yellow-100 md:mt-0 mt-2"
<img width="643" alt="image" src="https://github.com/acm-ucr/isa-website/assets/91030482/981328ce-f6e8-4e29-bd13-71708a3deb9c">

the join button looks a little misaligned here. what does the mobile responsiveness supposed to do here?

2024-02-09 23:08 UTC, seanquiambao approved these changes

2024-02-09 23:08 UTC, merged