Whatcompmarg
acm-ucr/isa-website pull request #114
Opened 2024-02-05 22:27 UTC by zalam007

![wc](https://github.com/acm-ucr/isa-website/assets/146377680/a2ab96f3-f5db-4396-a0e4-ea01bda29564)

2024-02-05 22:35 UTC, seanquiambao requested changes

2024-02-05 22:35 UTC, seanquiambao commented on src/components/home/What.jsx
> +      <p className="text-center text-2xl my-5 w-[90%]">
revert back the original lines of code and only change margining. you might have forgotten to pull from development branch

2024-02-05 22:35 UTC, seanquiambao commented on src/app/board/page.js
unstage this file from this branch, this is a separate issue.

2024-02-05 23:16 UTC, zalam007 commented
made changes, should be repushed

2024-02-06 06:23 UTC, seanquiambao requested changes
address some merge conflicts as well

2024-02-06 06:23 UTC, seanquiambao commented on src/app/board/page.js
the changes in the /app/board/page.js needs to be removed from this branch

2024-02-13 01:10 UTC, seanquiambao approved these changes

2024-02-13 01:10 UTC, merged