added Get Involved component
acm-ucr/isa-website pull request #47
Opened 2024-01-19 04:53 UTC by duvalincus

![image](https://github.com/acm-ucr/isa-website/assets/93236538/3188cb5d-df8e-4783-a61c-beb41227bbcc)

Adds the social sites and centers them. Not sure about the rectanglefill elements. 

Closes #34.

2024-01-19 05:13 UTC, seanquiambao requested changes

2024-01-19 05:13 UTC, seanquiambao commented on src/components/Involved.jsx
> +      <Title text={"Get Involved"} />
```suggestion
      <Title text="Get Involved" />
```

2024-01-19 05:13 UTC, seanquiambao commented on src/components/home/Social.jsx
>  const Icon = ({ icon, text, link }) => {
Rename function to social

2024-01-19 05:13 UTC, seanquiambao commented on src/data/home/Socials.js
> +    icon: <FaDiscord className="text-3xl isa-yellow-200" />,
for the className, you can create a const javascript string variable called class containing the CSS. This is so we can adjust all styling to all classNames with a single edit, incase we need to make adjustments
```suggestion
    icon: <FaDiscord className={class} />,
```

2024-01-19 05:13 UTC, seanquiambao commented on src/data/home/Socials.js
> +    icon: <FaDiscord className="text-3xl isa-yellow-200" />,
- icons are too small
- use yellow-100 instead

2024-01-19 05:13 UTC, seanquiambao commented on src/components/Involved.jsx
> +            ></Social>
```suggestion
            <Social
              key={index}
              text={social.name}
              link={social.link}
              icon={social.icon}
            />
```

2024-01-19 05:13 UTC, seanquiambao commented on src/components/home/Social.jsx
> +      className="flex flex-col cursor-pointer h-25 text-isa-yellow-200 items-center m-2.5"
a little more margining

2024-01-20 21:08 UTC, duvalincus commented
![image](https://github.com/acm-ucr/isa-website/assets/93236538/963b9fb2-6ffb-4992-a9de-22746226f65f)
latest commit change

2024-01-21 01:59 UTC, seanquiambao requested changes

2024-01-21 01:59 UTC, seanquiambao commented on src/data/home/Socials.js
> +const className = "text-5xl isa-yellow-200";
try `7xl`

2024-01-21 02:18 UTC, duvalincus commented
![image](https://github.com/acm-ucr/isa-website/assets/93236538/e1234d44-c376-4032-aad8-a3a4459e062b)
w/ 7xl

2024-01-21 02:22 UTC, seanquiambao approved these changes

2024-01-21 02:23 UTC, merged