About component
acm-ucr/isa-website pull request #67
Opened 2024-01-23 03:48 UTC by zalam007

2024-01-23 06:52 UTC, seanquiambao commented
add an image for your component and link your issue under development

2024-01-23 07:09 UTC, seanquiambao requested changes

2024-01-23 07:09 UTC, seanquiambao commented on src/components/home/About.jsx
> +            Indian Student Association-ISA at UCR serves the purpose to provide
make the text size a little bigger

2024-01-23 07:09 UTC, seanquiambao commented on src/components/home/About.jsx
> +      <Image src={cloud} alt="Picture of cloud" className="mt-[-58px] z-0" />
![image](https://github.com/acm-ucr/isa-website/assets/91030482/db92c036-fad4-481d-8b55-f07a7f49dd92)

the cloud doesn't fill the page width-wise

2024-01-23 07:09 UTC, seanquiambao commented on src/components/home/About.jsx
> +          <div className="text-center w-1/2 mx-auto mt-10">
you can put the whole CSS to its parent tag in line 14

2024-01-23 07:09 UTC, seanquiambao commented on src/app/page.js
> +      <About />
place this below the landing page

2024-01-23 07:09 UTC, seanquiambao commented on src/components/home/About.jsx
> +        <Image src={navlogo} alt="Picture of navlogo" />
scale logo a little bigger, you can use tailwindCSS to scale the image

2024-01-23 07:09 UTC, seanquiambao commented on src/components/home/About.jsx
> +      <div className="flex items-center px-32 z-1">
![image](https://github.com/acm-ucr/isa-website/assets/91030482/fc60743a-0c4f-42f3-9bf0-4d60db6cec8b)
logo should be closer to the texts

2024-01-26 06:43 UTC, zalam007 commented
![Uploading ab.png…]()

2024-01-26 06:43 UTC, zalam007 commented
![ab](https://github.com/acm-ucr/isa-website/assets/146377680/b483384f-0f17-4a1f-ada7-77e7eaa2053c)

2024-01-26 21:06 UTC, seanquiambao approved these changes

2024-01-26 21:30 UTC, merged