Added blue suns
acm-ucr/isa-website pull request #68
Opened 2024-01-23 05:07 UTC by duvalincus

Ran into some issues with the footer, may have to edit the positioning.

![image](https://github.com/acm-ucr/isa-website/assets/93236538/bca0d1f9-fb54-486c-a359-4c22e2637e3d)
![image](https://github.com/acm-ucr/isa-website/assets/93236538/a448fbf3-06d8-40ee-9fa7-abe3dc5a5b0f)

Closes #62.

2024-01-23 07:14 UTC, seanquiambao requested changes

2024-01-23 07:14 UTC, seanquiambao commented on src/components/Footer.jsx
> +    <div className="bg-gradient-to-r from-isa-blue-200 to-isa-blue-100 w-full p-2 fixed bottom-0">
revert this back to relative. fixing the footer will make the footer stick to window while scrolling, but we don't want that.

2024-01-23 07:14 UTC, seanquiambao commented on src/app/about/page.js
> +        className="absolute bottom-0 -left-[250px] h-[800px] w-[600px]"
- you can use tailwind scale to size the suns without using larger values
- make the suns a little bigger

2024-01-23 07:14 UTC, seanquiambao commented on src/app/about/page.js
> +        className="absolute top-0 -right-[250px] h-[700px] w-[600px]"
see same comments from the other sun

2024-01-24 04:18 UTC, duvalincus commented
![image](https://github.com/acm-ucr/isa-website/assets/93236538/270ce8df-6a9e-46ac-b3ad-bfcf09030818)
![image](https://github.com/acm-ucr/isa-website/assets/93236538/84a8fe69-562f-4bb3-b3c8-b2fa3e6fe26f)

Uses scale-140, and mimicks the hiss layout now.

2024-01-24 04:24 UTC, duvalincus commented
![image](https://github.com/acm-ucr/isa-website/assets/93236538/b3926c89-9133-4b50-b105-a24de710abb9)
![image](https://github.com/acm-ucr/isa-website/assets/93236538/25ff2446-54d2-402a-aa80-493c4e5378de)

Uses scale-140, mimicks HISS layout.

2024-01-24 06:15 UTC, seanquiambao approved these changes
lgtm!

2024-01-24 06:16 UTC, merged