Calendar Page
acm-ucr/isa-website pull request #78
Opened 2024-01-26 22:46 UTC by achen409

![image](https://github.com/acm-ucr/isa-website/assets/85457506/7e4f524a-8893-4424-8a02-e2ce754f789e)
![image](https://github.com/acm-ucr/isa-website/assets/85457506/bc70d385-33c8-4fda-8d9e-afd2f6001ff7)

2024-01-26 22:49 UTC, seanquiambao requested changes

2024-01-26 22:49 UTC, seanquiambao commented on src/app/events/page.js
> +        <Image
put the suns right behind the calendar component.

2024-01-27 00:42 UTC, achen409 commented
![image](https://github.com/acm-ucr/isa-website/assets/85457506/c3113dab-262d-43bb-ba35-e9b9971ab716)

2024-01-27 04:27 UTC, seanquiambao approved these changes

2024-01-27 04:27 UTC, merged